name: basicCI

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 2' # https://crontab.guru/#0_0_*_*_2
jobs:
  java_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      - run: gradle clean build

