name: basicCI

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2' # https://crontab.guru/#0_0_*_*_2
jobs:
  java_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v3.3.2
        with:
          gradle-version: 6.5
      - run: gradle clean build

